### ISSUE TITLE
Uploads stuck on extracting audio

### ISSUE THREAD

**Issue by anthkris** [awslabs/aws-video-transcriber#15]
Sorry to bother you again, but I just can't seem to get this app working smoothly! I've tried uploading two videos, both around 1 minute, and they keep getting stuck on extracting audio for hours and never advancing beyond that.

There is no error in the console. Cloudwatch indicates that the videos are successfully being put into Dynamo DB. The extract audio logs indicate:

```
2019-06-06T16:46:12.703Z cd193412-455d-403c-82a5-704ebf4ae320 [INFO] successfully put item with response:
{}
```
But there's nothing in any of the other logs and no files in S3.

Any tips on what I can do to fix this?

**Comment by jospas** [comment]
Hi its not problem at all, thanks for reaching out!

The system should probably be ported to Step Functions behind the scenes as asynchronous service calls that fail and don't produce the required file in S3 to trigger the next phase can cause processing to halt like you are seeing. The good news is once we fix the issue you can usually just copy and paste the file over itself in the S3 console to start the process again from a particular step (or use the replay button in the UI).

Can you please have a look at the following for me, I need some more information:

1. The CloudWatch logs for the next function **TranscribeAudio** If this function fails it should set the status of the processing status to errored but maybe there is an uncaught issue with the Lambda? The logs are quite verbose please attach the whole log for the failed run if it exists.

2. If that all looks good or there are no executions, its likely that the ElasticTranscoder job failed to run. Log into the console and have a look at the logs for the Elastic Transcoder job. I have seen issues with the default limits for the maximum number of Elastic Transcoder jobs being quite low at 4 pipelines. The system attempts to create these lazily on first run although this is caught well and reports as an error. If this job doesn't produce the MP3 extract (due to missing audio channel in the input video for example) the next process won't start!

3. The audio bucket created by the solution should also have an MP3 named using the video UUID extracted from the video (available from the UI or from the DynamoDB table). Can you please confirm this exists in S3 if step 2. succeeded? The next phase of the serverless pipeline kicks off when then this MP3 lands.

4. Can you please confirm the region you are deploying into? I have not tested all AWS regions and perhaps not all services are actually available in the regions I provide deployment to (I used the AWS Region Table to select target regions): https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/

Looking forward to getting some more information on this one, I'm intrigued!

J

**Comment by anthkris** [comment]
1. The CloudWatch logs for the next function TranscribeAudio: This is completely empty.

2. ElasticTranscoder job (looks like this is the problem, but I dont know how I deployed the app without the right roles): 
```
Preset   System preset: Audio MP3 - 128k | Preset | System preset: Audio MP3 - 128k | Preset ID   1351620000001-300040 | Preset ID | 1351620000001-300040
-- | -- | -- | -- | -- | --
Preset | System preset: Audio MP3 - 128k
Preset ID | 1351620000001-300040
Output Key   1f1e9505-8e4a-4688-862f-d0ff6812bb14.mp3 | Output Key | 1f1e9505-8e4a-4688-862f-d0ff6812bb14.mp3 | Status   Error | Status | Error
Output Key | 1f1e9505-8e4a-4688-862f-d0ff6812bb14.mp3
Status | Error
Status Details   2000  188b2db6-8833-4887-8e74-0e7ef396400b: The IAM role  arn:aws:iam::312726812299:role/ldtm-transcribe-prod-aws-captions-elastic-transcoder-role  either does not exist or has not granted Amazon Elastic Transcoder the  sts:AssumeRole permission. | Status Details | 2000  188b2db6-8833-4887-8e74-0e7ef396400b: The IAM role  arn:aws:iam::312726812299:role/ldtm-transcribe-prod-aws-captions-elastic-transcoder-role  either does not exist or has not granted Amazon Elastic Transcoder the  sts:AssumeRole permission. | Output Duration | Output Duration |  
Status Details | 2000  188b2db6-8833-4887-8e74-0e7ef396400b: The IAM role  arn:aws:iam::312726812299:role/ldtm-transcribe-prod-aws-captions-elastic-transcoder-role  either does not exist or has not granted Amazon Elastic Transcoder the  sts:AssumeRole permission.
Output Duration |  
```
3. I see a link in the DynamoDB for the audio, but nothing seems to actually exist in the S3 bucket: 
```
s3://prod-aws-captions-audio-us-east-1-312726812299/audio/1f1e9505-8e4a-4688-862f-d0ff6812bb14.mp3
```
4. Deployed in US East (N.Virginia)

**Comment by jospas** [comment]
Hi there,

I have seen this before it looks like you have perhaps previously deployed and removed this solution in this account using the previous stack name: 'ldtm'

As I lazily create the Elastic Transcoder Service (ETS) Pipelines during the encoding process and I haven't given them pipeline specific names they actually remain (at no cost) after stack removal but the underlying role they rely on has since been removed.

I will look to add pipeline creation to the custom lambda resource I use behind the CloudFormation stack (ETS pipelines are not supported in CloudFormation) so they they get created and removed with the stack, much tidier in hindsight.

The great news for you is to fix this issue simply delete the existing ETS pipelines and using the UI, restart processing for the videos and you should run end to end.

J

**Comment by anthkris** [comment]
That's done it! Thanks so much!
