### ISSUE TITLE
MyCustomResource Error

### ISSUE THREAD

**Issue by gborasio** [awslabs/aws-video-transcriber#24]
The cloudformation return me access denied when load the part MyCustomResource

**Comment by jospas** [comment]
Hi and thanks for your bug report!

I think the issue is likely a failure while I am copying the S3 objects to host the web application and attempting to marked them as public by object ACL.

A new setting was released for S3 whereby you can block public objects by ACL and I think this is the default for new internal AWS accounts.

Can you please adjust this setting and try again? Beware the CloudWatch logs may still exist for the custom resource and you may need to clean these up by hand before deploying again.

**Comment by deki** [comment]
I was facing the same issue and can confirm that modifying the block public objects setting fixed it for me.

**Comment by MGSAWS** [comment]
same here, modifying the s3 setting fixed the problem
